libraries:                                      # Library mappings must have a colon (:) placed after them
  # Movies:
  #   metadata_path:
  #     - file: config/Movie.yml
  #     - file: config/Metadata.yml
  #     - file: config/Holiday.yml
  #     - file: config/Special_Collections.yml
  #     - file: config/Director.yml
  #     - file: config/Studio.yml
  #     - file: config/Genre.yml
  #     - file: config/Overlays.yml
  # Anime:
  #   sonarr:
  #     url: http://localhost:7875/
  #     token: anime
  #     add_missing: false
  #     add_existing: true
  #     root_folder_path: E:\Anime
  #     monitor: all
  #     quality_profile: Anime
  #     language_profile: English
  #     series_type: anime
  #     season_folder: true
  #     tag:
  #     search: false
  #     cutoff_search: false
  #     sonarr_path:
  #     plex_path:
  #   metadata_path:
  #     - file: config/Anime.yml
  TV Shows:
    metadata_path:
      - file: config/TV_Shows.yml
      - file: config/Overlays.yml
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  dimensional_asset_rename: true
  download_url_assets: false
  show_missing_season_assets: false
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  missing_path: config/missing
  show_missing: true
  show_missing_assets: false
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user: all
  verify_ssl: true
webhooks:                                       # Can be individually specified per library as well
  error:
  run_start:
  run_end:
  changes:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: SECRET
  token: SECRET
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: SECRET
  language: en
tautulli:                                       # Can be individually specified per library as well
  url: http://192.168.1.12:8181
  apikey:
omdb:
  apikey:
notifiarr:
  apikey:
anidb:                                          # Not required for AniDB builders unless you want mature content
  username: jch0tsh0t
  password: SECRET
radarr:                                         # Can be individually specified per library as well
  url: http://localhost:7879/
  token: SECRET
  add_missing: false
  add_existing: false
  root_folder_path: F:\Movies (4k)
  monitor: true
  availability: announced
  quality_profile: Ultra-HD
  tag:
  search: false
  radarr_path:
  plex_path:
sonarr:                                         # Can be individually specified per library as well
  url: http://localhost:7874/
  token: SECRET
  add_missing: false
  add_existing: false
  root_folder_path: E:\Shows (4k)
  monitor: true
  quality_profile: Ultra-HD
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
trakt:
  client_id: SECRET
  client_secret: SECRET
  authorization:
    access_token: 53690662649a5f6cf25bed8e616725cebc57a07fe174baf52a108394c57729ea
    token_type: Bearer
    expires_in: 7889238
    refresh_token: b8627d05945aa5d28a520f4a48c707fd3608f88c31d3c2c295616dee338d5ae3
    scope: public
    created_at: 1675702481
mal:
  client_id: SECRET
  client_secret: SECRET
  authorization:
    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjYxNDkzYzBiOGQzNGY5YjViYTY0OGEwNzg2MTgyODdlNGJkMWQxOTJjMjFlZTlmYTgzNTZmZGVlN2MxMDk0OWM4YTIyNzRiZWE0ZmEzZDUzIn0.eyJhdWQiOiJkNGQ3MTdlNzUyYTk2MDBmMjA0YjRjNTI0ODk1YjFmMiIsImp0aSI6IjYxNDkzYzBiOGQzNGY5YjViYTY0OGEwNzg2MTgyODdlNGJkMWQxOTJjMjFlZTlmYTgzNTZmZGVlN2MxMDk0OWM4YTIyNzRiZWE0ZmEzZDUzIiwiaWF0IjoxNjc4MTQyNDg2LCJuYmYiOjE2NzgxNDI0ODYsImV4cCI6MTY4MDgxNzI4Niwic3ViIjoiNDc1MjI4NiIsInNjb3BlcyI6W119.FQHYMyPpcbFsc7FXhWqHghS59HcYGT70KU1O-e1sKD9iZzI-Ql_JaxawBxDDwv_kzcvQdLlCQfE8wH_gOljk2baNlsJNSGCnl87fRShL6DzI-kZ2sjDMR5Y4MlPcbVKTODOqquMbJmFFOG3-IAcWz_TZpnWpgB47q1Xc1RqRghVcOStOqAcyU3cCgscORRDTNMy3p_RUQxdi99tat1Coeqwz7KT38YuSoczdpjLNX2MIYR84_qjyc_AZ60hm6FLdbLtwl9FmJZpVTjt6S-g6Bzn7YPRmCGQRNIR27yPpd99zURyYrWVACCiGdtSb-3wmLarvKOWTqbzdrmnPKX2Ofg
    token_type: Bearer
    expires_in: 2674800
    refresh_token: def50200b8e5a101e01e0608f14d2374106fa52f1e29d333c3de79ed0598bc7a4dddaeb791bdd429f5a07e6be99d2f61f6a70c887054e932ea3e28c909291bfac2aa221a8bc67486dfe02d40aedaa818b106a81bde912523e8538b671151e0a52dbd4f1acd62ad6c78b09fb2293d762663134adcb62474ab0c5e277c8e8f90a08ad351384ba20566909711f059554d54ec75c78b53c880ecb8a8806506958e0a242ab73faaec056faa9d3e828213c62f8d1a99f805327c242f1f4cf243d5cb332195120997e3868816aeccb08f7fdd6321cfe5ac21f02b139076158c8fb75623e8bb8ded9db98111c8fdabcb06865b68c079e94020a2eb17312a78cb04ecd14de2fb75e43b6a82e48a2ae08f0290ef2ac5b259ad1db4e23ee2e583fd44aba4a5a301c203e844f00d250d4fd73d7fa54ee160ed7b93ac8cd5c6b91b1b8e7c1566bb5391facdec384c852dbcf9e262842abba472ba09c13b8d4a56b04637d3e1a01843f036f0cc3be51d34cd970506b009a0137cb2006ee8b6f52569907762de1abe9828e17ed4c767
