libraries:                                      # Library mappings must have a colon (:) placed after them
  Movies:
    metadata_path:
      # - file: config/Movie.yml
      - file: config/Metadata.yml
      - file: config/Holiday.yml
      - file: config/Special_Genre.yml
      - file: config/Director.yml
      - file: config/Studio.yml
      - file: config/Genre.yml
      - file: config/Overlays.yml
  Anime:
    sonarr:
      url: http://localhost:7875/
      token: anime
      add_missing: false
      add_existing: true
      root_folder_path: F:\Anime
      monitor: all
      quality_profile: Anime
      language_profile: English
      series_type: anime
      season_folder: true
      tag:
      search: false
      cutoff_search: false
      sonarr_path:
      plex_path:
    metadata_path:
      - file: config/Anime.yml
  TV Shows:
    metadata_path:
      - file: config/TV_Shows.yml
      - file: config/Overlays.yml
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  dimensional_asset_rename: true
  download_url_assets: false
  show_missing_season_assets: false
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  missing_path: config/missing
  show_missing: true
  show_missing_assets: false
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user: all
  verify_ssl: true
webhooks:                                       # Can be individually specified per library as well
  error:
  run_start:
  run_end:
  changes:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: SECRET
  token: SECRET
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: SECRET
  language: en
tautulli:                                       # Can be individually specified per library as well
  url: http://192.168.1.12:8181
  apikey:
omdb:
  apikey:
notifiarr:
  apikey:
anidb:                                          # Not required for AniDB builders unless you want mature content
  username: jch0tsh0t
  password: SECRET
radarr:                                         # Can be individually specified per library as well
  url: http://localhost:7879/
  token: SECRET
  add_missing: false
  add_existing: false
  root_folder_path: F:\Movies (4k)
  monitor: true
  availability: announced
  quality_profile: Ultra-HD
  tag:
  search: false
  radarr_path:
  plex_path:
sonarr:                                         # Can be individually specified per library as well
  url: http://localhost:7874/
  token: SECRET
  add_missing: false
  add_existing: false
  root_folder_path: E:\Shows (4k)
  monitor: true
  quality_profile: Ultra-HD
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
trakt:
  client_id: SECRET
  client_secret: SECRET
  authorization:
    access_token: 53690662649a5f6cf25bed8e616725cebc57a07fe174baf52a108394c57729ea
    token_type: Bearer
    expires_in: 7889238
    refresh_token: b8627d05945aa5d28a520f4a48c707fd3608f88c31d3c2c295616dee338d5ae3
    scope: public
    created_at: 1675702481
mal:
  client_id: SECRET
  client_secret: SECRET
  authorization:
    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjA4Y2ZkYWRkMDJlYmZjNzNkZWRkZGIxMzY2NzEyM2I3MTYzYTBmOWRhODc0MzkxYjc1MTBlNTg5MzM0OTBjNjA2YzdjNmQ5NTMxMzdmNDIwIn0.eyJhdWQiOiJkNGQ3MTdlNzUyYTk2MDBmMjA0YjRjNTI0ODk1YjFmMiIsImp0aSI6IjA4Y2ZkYWRkMDJlYmZjNzNkZWRkZGIxMzY2NzEyM2I3MTYzYTBmOWRhODc0MzkxYjc1MTBlNTg5MzM0OTBjNjA2YzdjNmQ5NTMxMzdmNDIwIiwiaWF0IjoxNjc1Njc0MzA0LCJuYmYiOjE2NzU2NzQzMDQsImV4cCI6MTY3ODA5MzUwNCwic3ViIjoiNDc1MjI4NiIsInNjb3BlcyI6W119.PLa9a5JOu9zZZXYINLdbFuVuwWQcHGNyQug8iOJpLULmcqoEN4retEbCILCHOgNKNPLONUjEhGTUeGVJVzZR5uueB5qJA3m8tK4Qm85pgtQwwlN_zLqK9e2-97ptVT0Qfowjo30Fx_EeafvGbUro7DipxA-_KhGffhM2FeJca4gj_cnpwDYJB00_iZWcNpLEtsbBf0t8OisVnOO7GCCPt7ytcktlVUCKX6165y_LP5_CZiuwSHxa3G7893ZGgNG-Mj1w20FttjLnohev220aaqxhaTQpbJEwCCKWoSpMoo2Lfz62D8Jjo0Igbw5V7bbdy4A66XHWEQTGndvwBzBsHQ
    token_type: Bearer
    expires_in: 2419200
    refresh_token: def50200d270fccc6867273c6655b41d37c0a93d945ee2cdd0c661ab9179c033c2d0e316b5038a4399e3917d3fd39d69d9bc6fe0f1e126c94733287dfb7051b96446a6ec9436c4e732c183a74f90627d649d5f9211cc72f7953df66a3723663057c18eba77c80f05bc0e0b533e1a29fbd6c6ff6fd07ce342ae0f37c4b714b97aee80a03b5d76ff632787a19bb9b94ae3fa054f21925e700774659d8cbd48b46bc81c3d1cd288b8e95123d51cad206afb595c3752d5cb6180233f43477e32cc91c4cca843fe370484f11f6cbda8069a1f374e4ba434421ec0b71b951e1344007bdc51adb24be9197d3eb3712daf927cda906697514194b3237b1e430cc419f0e9a88f273764ccd33903ea1d550c343f6de09847b3957d3321b020a86c21ff66e8761f4aa072eec47cf1a6e05612c08c9692157ea3d6035176197564cf3d5a7a8904cf49aa55ec59334e2e638a4c550576015761d75173de68e092e68ec35c38b5b85cb179f5dff74cd3b53a987e8a7682e4389de60f694ca9807703bb6cf9b0398343c944b9aa96c1
