libraries:                                      # Library mappings must have a colon (:) placed after them
  # Movies:
  #   metadata_path:
  #     - file: config/Movie.yml
  #     - file: config/Metadata.yml
  #     - file: config/Holiday.yml
  #     - file: config/Special_Genre.yml
  #     - file: config/Director.yml
  #     - file: config/Studio.yml
  #     - file: config/Genre.yml
  #     - file: config/Overlays.yml
  Anime:
    sonarr:
      url: http://localhost:7875/
      token: anime
      add_missing: false
      add_existing: true
      root_folder_path: F:\Anime
      monitor: all
      quality_profile: Anime
      language_profile: English
      series_type: anime
      season_folder: true
      tag:
      search: false
      cutoff_search: false
      sonarr_path:
      plex_path:
    metadata_path:
      - file: config/Anime.yml
  TV Shows:
    metadata_path:
      - file: config/TV_Shows.yml
      - file: config/Overlays.yml
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  dimensional_asset_rename: true
  download_url_assets: false
  show_missing_season_assets: false
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  missing_path: config/missing
  show_missing: true
  show_missing_assets: false
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_user: all
  verify_ssl: true
webhooks:                                       # Can be individually specified per library as well
  error:
  run_start:
  run_end:
  changes:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: SECRET
  token: SECRET
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: SECRET
  language: en
tautulli:                                       # Can be individually specified per library as well
  url: http://192.168.1.12:8181
  apikey:
omdb:
  apikey:
notifiarr:
  apikey:
anidb:                                          # Not required for AniDB builders unless you want mature content
  username: jch0tsh0t
  password: SECRET
radarr:                                         # Can be individually specified per library as well
  url: http://localhost:7879/
  token: SECRET
  add_missing: false
  add_existing: false
  root_folder_path: F:\Movies (4k)
  monitor: true
  availability: announced
  quality_profile: Ultra-HD
  tag:
  search: false
  radarr_path:
  plex_path:
sonarr:                                         # Can be individually specified per library as well
  url: http://localhost:7874/
  token: SECRET
  add_missing: false
  add_existing: false
  root_folder_path: E:\Shows (4k)
  monitor: true
  quality_profile: Ultra-HD
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
trakt:
  client_id: SECRET
  client_secret: SECRET
  authorization:
    access_token: 15a0fefde6a91e9a6489ea61ec85b0f0ab08b8ac7566a115173824555a03c7b8
    token_type: Bearer
    expires_in: 7889238
    refresh_token: ffd19c898c07d1d8f7b51e025508729a838ebace80680355b90580b1c24b60b1
    scope: public
    created_at: 1667759310
mal:
  client_id: SECRET
  client_secret: SECRET
  authorization:
    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjhjMDA3ZTljZTg3M2E0MjFiNjBiYWMxZjQ5YWQ2N2RmMDJiNTFlZjc3ZjVhNzJmYmZmYjM3MjBkMWU2N2ZkMGQ1N2QzODE2M2ZhNTcyZWNlIn0.eyJhdWQiOiJkNGQ3MTdlNzUyYTk2MDBmMjA0YjRjNTI0ODk1YjFmMiIsImp0aSI6IjhjMDA3ZTljZTg3M2E0MjFiNjBiYWMxZjQ5YWQ2N2RmMDJiNTFlZjc3ZjVhNzJmYmZmYjM3MjBkMWU2N2ZkMGQ1N2QzODE2M2ZhNTcyZWNlIiwiaWF0IjoxNjcyOTk1NjA0LCJuYmYiOjE2NzI5OTU2MDQsImV4cCI6MTY3NTY3NDAwNCwic3ViIjoiNDc1MjI4NiIsInNjb3BlcyI6W119.IkDzmvSc0YRUH03f3wsTSfHtqAVLoR8qEoNYbUubagxK_-cKaN52H2857cshO9-X4_HnfFPvQZOIqGmfinF092zW9YkxddHuEcivUndjHkEmIdupC4JSaEBFjNcT4YCTx7Bw3jnw4lhYMRPVI-0f12NqagHBrXaJN6UF09vfj33cill0nxBUJDE4imBiuGP5PBLhMY1Q8CEAUWrchYC8tt8RU3_QPWRGmkMUKYJeLm_1L8hulWAvNsG0xL2a00OekyBFFvPxP2KxN-KMhqjdp6dZdge8RhBI-So7OuZg8jrbaqYy2G38EhgPWER19xeskPAjKpKDsY0sVXt1cM-bhg
    token_type: Bearer
    expires_in: 2678400
    refresh_token: def5020052afbedaeeeeed5becc1655c47777e38efd458f54250ee14698925fc7e6e95ff20d591e8c32b8022172a6f50bee9a5ce8d8faa482530a3b7a65c32f4ff7aadf531452c887f6f22f4597c6ab51eeade49091173bc07600f60272937f8611027845cc41f7b29cc20d138b3be4c0a118711f7cffcb6a85e1dc9c8aaf852422b1e9e29ec0419ed3ffd9d23f6a8e3ea11c659c954efdaed95b06728b2d30870a2b36ec8b57a8a118e8751bbecd013ea28753504df261c4180a879b853f5cc376e9a07bd2a5c054e79aa079037980be360d31894dec07c51485ebc48790399223f9f9ad7d998cbb5d1798e188275afc04c3e64d5c32b3cb3c66e16950c483648232eca289d4db0e52eee85a4e2370183d2d7efd43cd4f14aae5bb79bb370068eafc9b3517aa6bcf2a823ad95b770ebc2d144669afa38729a2465bc3a1dfd435ce59fb0abea375b331d67541a3ee05ef7a943d5ec83833629109212f93059e5fb1a0ecd534485b8d5c5a4cef1cdb767b93d13bc2e2be72ade66770f763b48123f2c1aaaf1c6da91
